#!/usr/bin/env bash

ROOT=$(cd "$(dirname "$0")" && pwd)

set -ue

VERSION=$(cat "$ROOT/VERSION")

cat << EOS > "$ROOT/version.go"
// Code generated by generate.sh; DO NOT EDIT.
package forwarder
const version = "$VERSION"
EOS

perl -pe 's!__VERSION__!'"$VERSION"'!g' "$ROOT/template.template.yaml" > "$ROOT/template.yaml"
